
version: '3.11'

services:
  yolo-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - FLASK_ENV=production
    restart: unless-stopped